[package]
name = "mandel"
version = "0.1.0"
authors = ["Johannes Hoff <johshoff@gmail.com>"]

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies]
time = "0.1"
